apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp10
    app.kubernetes.io/part-of: testapp10
  name: testapp10qamg
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: testapp10
    weight: null
status: {}
