apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp10
    app.kubernetes.io/part-of: testapp10
  name: testapp10
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: testapp10
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: testapp10
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/klakshma-tenant/testapp10/testapp10@sha256:1fc5f050e8a5107884017ad41ec9e3d956759a69e062ef308e3b85d192b67ed1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
